[phases.setup]
nixPkgs = ["nodejs", "python3", "ffmpeg"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["python3 -m ensurepip && python3 -m pip install yt-dlp"]

[start]
cmd = "node server.js"